spring:
  application:
    name: library-events-consumer
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-consumer-group
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: library-events
      database: library-events
      username: lbr-evnt-listener
      password: qwerty

app:
  topics:
    library-events: library-events
    retry: library-events.RETRY
    dlt: library-events.DLT

server:
  port: 8091
