spring:
  application:
    name: library-event-producer
  banner:
    location: classpath:banner.txt
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094

app:
  libraryEventsTopicName: library-events

server:
  port: 8090
